title: VS's blog
email: viacheslav@savinkov.me
description: >
  Viacheslav Savinkov's personal blog
baseurl: ""
url: "https://savinkov.me"
icon-16x16: /assets/images/icon/favicon.ico
icon-32x32: /assets/images/icon/favicon.ico
theme-color: {
  default-color: green,
  home-color: green,
  about-color: red,
  archive-color: pink,
  links-color: purple,
  tags-color: blue
}
mobile-hp: /assets/images/M.png
mobile-bg: theme
header-bg: /assets/images/bg.png
disqus-shortname: savinkov-me
cdn: false
cdnurl:
google_analytics:
defaultAuthor:
defaultAuthorImage: assets/images/tx.jpg
manyAuthors: true
gallery: false
markdown: kramdown
exclude: [vendor]
