title: VS's blog
email: alligators@list.ru
description: > # this means to ignore newlines until "baseurl:"
  Viacheslav Savinkov's personal blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
icon-16x16: /assets/images/icon/favicon.ico
icon-32x32: /assets/images/icon/favicon.ico
theme-color: { 
  default-color: green, 
  home-color: green,
  about-color: red,
  archive-color: pink,
  links-color: purple,
  tags-color: blue
} 
mobile-hp: /assets/images/M.png
mobile-bg: theme
header-bg: /assets/images/bg.png
disqus-shortname: savinkov
cdn: false
cdnurl: 
google_analytics:
defaultAuthor: Slava
defaultAuthorImage: assets/images/tx.jpg
manyAuthors: true
gallery: false
markdown: kramdown
exclude: [vendor]
